config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :image, presence: true  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]
  before_action :check_valid_user, only: %i[ edit update destroy ]

  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all.order(created_at: :desc)
  end

  # GET /pictures/1 or /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures or /pictures.json
  def create
    @picture = current_user.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:image, :comment, :image_cache)
    end

    def check_valid_user
      redirect_to pictures_path unless @picture.user_id == current_user.id
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'Log in failed'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'Successfully Logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FB Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="top-breadcrumb">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to 'Home', pictures_path %></li>
                <% if logged_in? %>
                  <li class="breadcrumb-item"><%= link_to 'Profile', user_path(current_user.id) %></li>
                  <li class="breadcrumb-item"><%= link_to 'Logout', session_path(current_user.id), method: :delete %></li>
                <% else %>
                  <li class="breadcrumb-item"><%= link_to 'Sign up', new_user_path %></li>
                  <li class="breadcrumb-item"><%= link_to 'Login', new_session_path %></li>
                <% end %>
              </ol>
            </nav>
          </div>
        </div>
      </div>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>    
      <%= yield %>
    </div>
    <script>
      $(document).ready(function () {
        bsCustomFileInput.init();
      });
    </script>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h4>
      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card social-timeline-card">
    <h5 class="card-header">What are you gonna share?</h5>
    <div class="card-body">
      <div class="form-group">
        <div class="custom-file">
          <%= form.file_field :image, class: 'custom-file-input' %>
          <%= form.label :image, 'Choose file', class: 'custom-file-label' %>
          <%= form.hidden_field :image_cache %>
        </div>
        <p></p>
        <%= image_tag(@picture.image.url, class: 'img-fluid') if @picture.image && @picture.image.url %>
      </div>
      <div class="form-group">
        <%= form.label :comment, class: 'card-title' %>
        <%= form.text_area :comment, class: 'form-control', rows: '3', placeholder: 'What is the story?' %>
      </div>
      <div class="btn-toolbar justify-content-between">
        <div class="btn-group">
          <%= form.submit 'Post', class: 'btn btn-light' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<div class="row">
  <div class="col">
    <h1>Confirmation</h1>
    <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
      <div class="card">
        <div class="card-body">
          <div class="form-group">
            <%= image_tag(@picture.image.url, class: 'img-fluid') if @picture.image && @picture.image.url %>
            <%= form.hidden_field :image_cache %>
          </div>
          <div class="form-group">
            <p class="card-title">Comment</p>
            <p class="card-text"><%= @picture.comment %></p>
            <%= form.hidden_field :comment %>
          </div>
          <%= form.submit 'Post', class: 'btn btn-light' %>
        </div>
      </div>
    <% end %>
    <%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :comment %>
      <%= form.submit 'Back', name: 'back', class: 'btn btn-link' %>
    <% end %>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="row">
  <div class="col">
    <h1>Editing Picture</h1>
    <%= render 'form', picture: @picture %>
    <%= link_to 'Show', @picture, class: 'btn btn-link' %> |
    <%= link_to 'Back', pictures_path, class: 'btn btn-link' %>
  </div>
</div>

app/views/pictures/index.html.erb
<main>
  <div class="row">
    <div class="col-lg-3">
      <%= link_to 'Post a picture', new_picture_path, class: 'btn btn-primary btn-block' %>
      <br>
      <div class="card">
        <div class="card-body">
          <div class="h5 text-blue">@<%= current_user.name %></div>
          <div class="h7"><strong>Name:</strong> <%= current_user.name %></div>
          <div class="h7"><strong>About:</strong> Web developer, Python, Ruby, etc.</div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">Followers</div>
            <div class="h5">52,342</div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">Following</div>
            <div class="h5">6,758</div>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-lg-9 gedf-main">
      <% @pictures.each do |picture| %>
        <div class="card social-timeline-card">
          <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
              <div class="d-flex justify-content-between align-items-center">
                <div class="mr-2">
                  <img class="rounded-circle" width="45" src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="">
                </div>
                <div class="ml-2">
                  <div class="h5 m-0 text-blue">@<%= picture.user.name %></div>
                  <div class="h7 text-muted"><%= picture.user.name %></div>
                </div>
              </div>
              <div>
                <div class="dropdown">
                  <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-ellipsis-h"></i>
                  </button>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                    <%= link_to 'Show', picture, class: 'dropdown-item' %>
                    <% if picture.user_id == current_user.id %>
                      <%= link_to 'Edit', edit_picture_path(picture), class: 'dropdown-item' %>
                      <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item text-danger' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="text-muted h7 mb-2">
              <i class="far fa-clock"></i> <%= picture.created_at.strftime('%Y/%m/%d %H:%M') %>
            </div>
            <p class="card-text"><%= picture.comment %></p>
            <p><%= image_tag picture.image.url, class: 'img-fluid' %></p>
          </div>
          <div class="card-footer">
            <a href="#" class="card-link"><i class="fab fa-gratipay"></i> Like</a>
            <a href="#" class="card-link"><i class="fas fa-comment"></i> Comment</a>
            <a href="#" class="card-link"><i class="fas fa-share"></i> Share</a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/pictures/new.html.erb
<div class="row">
  <div class="col">
    <h1>Post a new picture</h1>
    <%= render 'form', picture: @picture %>
    <%= link_to 'Back', pictures_path, class: 'btn btn-link' %>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="card">
      <div class="card-body">
        <div class="h5 text-blue">@<%= current_user.name %></div>
        <div class="h7"><strong>Name:</strong> <%= current_user.name %></div>
        <div class="h7"><strong>About:</strong> Web developer, Python, Ruby, etc.</div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <div class="h6 text-muted">Followers</div>
          <div class="h5">52,342</div>
        </li>
        <li class="list-group-item">
          <div class="h6 text-muted">Following</div>
          <div class="h5">6,758</div>
        </li>
      </ul>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="text-muted h7 mb-2">
      <i class="far fa-clock"></i> <%= @picture.created_at.strftime('%Y/%m/%d %H:%M') %>
      posted by @<%= @picture.user.name %>
    </div>
    <p><%= @picture.comment %></p>
    <p><%= image_tag @picture.image.url, class: 'img-fluid' %></p>
    <% if @picture.user_id == current_user.id %>
      <%= link_to 'Edit', edit_picture_path(@picture), class: 'btn btn-link' %> |
    <% end %>
    <%= link_to 'Back', pictures_path, class: 'btn btn-link' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="form-signup">
  <h1 class="h3 mb-3 font-weight-normal">Sign up</h1>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@user.errors.count, 'error') %> prohibited this <%= @user.name %> from being saved:</h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Your name' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', placeholder: 'Email address' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Type password again' %>
    </div>
    <%= f.submit "Create my account", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>'s page</h1>
<p>E-mail address: <%= @user.email %></p>